trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern

from . import views

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('edit/', views.edit, name="edit"),
    path('suspend/', views.suspend, name="suspend"),
    path('display_account/', views.display_account, name="display_account"),
    path('request/', views.customer_request, name="customer_request")
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('filter/<str:weekly_pickup_day>', views.filter, name="filter"),
    path('route/', views.route, name="route"),
    path('account_info/', views.account_info, name="account_info"),
    path('registration/', views.registration, name="registration")
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% if user.is_authenticated %}
  {% for group in user.groups.all%}
    {% if group.name == "Customers" %}
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'customers:edit' %}">Change My Pickup Day</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'customers:customer_request' %}">Request One-Time Pickup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'customers:suspend' %}">Suspend My Account</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'customers:display_account' %}">Account Info</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
        </li>
      </ul>
    {% elif group.name == "Employees" %}
        <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'employees:index' %}">Daily View</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'employees:route' %}">Change Route</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'employees:account_info' %}">Account Info</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
        </li>
      </ul>
    {% endif %}
  {% endfor %}
{% endif %}
  <main>
    <h1>{% block header %} {% endblock %}</h1>
    {% block content %}
    {% endblock %}
  </main>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
</body>
</html>
{# This is the parent template that should be extended by any other view you create #}
{# Todo: Add navbar links, link to stylesheets, style layout #}

trash_collector/templates/home.html
{% extends 'base.html' %}

{% block title %} Home Portal {% endblock %}

{% block header %} Home Portal {% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attempt to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in. Please log in or create an account.</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:register' %}">Sign Up</a>
{% endif %}
{% endblock %}

{# This is the home page that allows a logged out user to register or log in #}