trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('filter/<str:weekly_pickup_day>', views.filter, name="filter"),
    path('route/', views.route, name="route"),
    path('account_info/', views.account_info, name="account_info"),
    path('registration/', views.registration, name="registration")
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models

# Create your models here.

class Employee(models.Model):
    name = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)
    zip_code = models.CharField(max_length=50)

    def __str__(self):
        return self.name

trash_collector/employees/views.py
from customers.models import Customer
from .models import Employee
from django.http import HttpResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.apps import apps
from django.urls import reverse
from django.http.response import HttpResponseRedirect



# Create your views here.


def index(request):
    # This line will get the Customer model from the other app, it can now be used to query the db for Customers
    all_customers = apps.get_model('customers.Customer')
    context = {
        'all_customers': all_customers
    }
    return render(request, 'employees/index.html', context)

def filter(request, weekly_pickup_day):
    filter_day = Customer.objects.filter(weekly_pickup_day=weekly_pickup_day)
    context = {
        'filter_day':filter_day
    }
    return render(request, 'employees/filter.html', context)
    
def route(request):
    change_route = Employee.objects.get(user=request.user)
    if request.method == "POST":
        change_route.zip_code= request.POST.get('zip_code')
        change_route.save()
        return HttpResponse(reverse('employees:index'))
    else:
        context = {
            'change_route': change_route
        }
        return render(request, 'employees/route.html', context)

def account_info(request):
    employees = Employee.objects.get(user=request.user)
    context = {
        'employees': employees
    }
    return render(request, 'employees/account_info.html', context)

def registration(request):
    if request.method == "POST":
        name = request.POST.get('name')
        user = request.user
        zip_code = request.POST.get('zip_code')
        new_employee = Employee(name=name, user=user, zip_code=zip_code)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/registration.html')

trash_collector/employees/templates/employees/account_info.html
{% extends 'base.html' %}

{% block title %} Employee Account Info {% endblock %}

{% block header %}<h2>Account Information</h2>{% endblock %}

{% block content %}

<table class = "table table-striped">
    <tbody>
        <tr>
            <td>Zip Code</td>
            <td>{{employees.zip_code}}</td>
        </tr>
        <tr>
            <td>Zip Code Responsibility</td>
            <td>{{employees.zip_code}}</td>
    </tbody>
</table> 
  
{% endblock %}

trash_collector/employees/templates/employees/filter.html
{% extends 'base.html' %}

{% block title %} Employee Filter Home {% endblock %}

{% block header %}  {% endblock %}

{% block content %}
<h1>Today's pickups</h1>

{% if customer %}

{% for customer in all_customers %}
    {{customer.name}}
{% endfor %}

{% else %}
Not working

{% endif %}
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %}Employee Home{% endblock %}
{% block header %} Weekdays
{% endblock %}

{% block content %}
{% if user.is_authenticated %} 

<a href="{% url 'employees:filter' 'Monday' %}">Monday</a><br />
<a href="{% url 'employees:filter' 'Tuesday' %}">Tuesday</a><br />
<a href="{% url 'employees:filter' 'Wednesday' %}">Wednesday</a><br />
<a href="{% url 'employees:filter' 'Thursday' %}">Thursday</a><br />
<a href="{% url 'employees:filter' 'Friday' %}">Friday</a><br />

{% else %}
  <p>You are at the employee index, but you are not logged in.</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:register' %}">Sign Up</a>

{% endif %}
{% endblock %}

trash_collector/employees/templates/employees/registration.html
{% extends 'base.html' %}

{% block title %} Employee Registration Home {% endblock %}

{% block header %} Emplyee Registration Home {% endblock %}

{% block content %}
<h1> Please fill out the following form </h1>
<form action="{% url 'employees:registration' %}" method="post">
    {% csrf_token %}
    Name: <input type="text" name="name" id="name"><br />
    Zip Code: <input type="text" name="zip_code" id = "zip_code"><br />
    <input type="submit" value="Register">
</form>
{% endblock %}

trash_collector/employees/templates/employees/route.html
{% extends 'base.html' %}

{% block title %} Employee Route {% endblock %}

{% block header %}{% endblock %}

{% block content %}

<p>If you would like to change your area of responsibility, please enter your desired location below.</p>
<form action="{% url 'employees:route' %}" method="post">
    {% csrf_token %}
    Zip Code: <input type="text" name="zip_code" value="{{change_route.zip_code}}"><br />
    <input type="submit" value="Change">
</form>

{% endblock %}